#!env bash
echo 1

# Do not install if running on NixOS
if [ -d '/usr/local/bin' ];
then
  # Install Starship if not already installed
  if [ ! -f '/usr/local/bin/starship' ];
  then
    curl -sS https://starship.rs/install.sh > starship-installer.sh
    sh starship-installer.sh -y
    rm starship-installer.sh
  fi
fi

# Install NeoVim config - Must use v2.0 as later versions change the project structure
git clone --depth 1 --branch v2.0 https://github.com/NvChad/NvChad.git ~/.config/nvim
# Remove default custom config
if [[ -d ~/.config/nvim/lua/custom ]]; then rm -r ~/.config/nvim/lua/custom; fi
# Link managed custom config
ln -s ~/nvim-lua-custom ~/.config/nvim/lua/custom

# Find the host's domain
if [[ $(uname -a | grep -i Linux) ]];
then
  domain=$(hostname -d)
elif [[ $(uname -a | grep -i MINGW64_NT) ]];
then
  domain=$(systeminfo | grep Domain | sed 's/Domain: *//')
else
  # Cannot determine domain
  exit
fi

# Set git user info based on domain
if [[ $domain == *"frasers.group" ]];
then
  git config --global user.email 103182756+alex-kitching-fg@users.noreply.github.com
  git config --global user.signingkey 507A2D42E4BFA925
else
  git config --global user.email akitching@users.noreply.github.com
  git config --global user.signingkey 413E4D58
fi
