#!/bin/bash

# Install Starship
curl -sS https://starship.rs/install.sh > starship-installer.sh
sh starship-installer.sh -y
rm starship-installer.sh

# https://github.com/DoomHammer/dotfiles/blob/master/.config/yadm/bootstrap
configure_vim() {
  # Install vim-plug for Vim
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim +'PlugInstall --sync' +qa
}

configure_vim
